config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :events, except: %i[edit update] do
    resources :participants, only: [:create]
    get "pairs", to: "events#assigning"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :participants, dependent: :destroy

  validates :title, :maximum_amount, presence: true
end

app/models/participant.rb
class Participant < ApplicationRecord
  belongs_to :event

  validates :name, :email, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :events

  validates :email, presence: true
  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
    @participant = Participant.new
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.user = current_user
    if @event.save
      redirect_to event_path(@event)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to events_path(@event), status: :see_other
  end

  def assigning
    @event = Event.find(params[:event_id])
    @participants = @event.participants
    receivers = @participants
    @participants.each do |participant|
      # 1.) Pick a sample name from the participants array without first name as target.
      target = (receivers - [participant]).sample.name
      # 2.) Update target field of participant with the name drawn from sample.
      participant.update(target:)
      # 3.) Remove target from list permanently.
      receivers -= [Participant.find_by(name: target)]
    end
  end

  private

  def event_params
    params.require(:event).permit(:title, :maximum_amount, :participants)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  def create
    @event = Event.find(params[:event_id])
    @participant = Participant.new(participant_params)
    @participant.event = @event
    if @participant.save
      redirect_to event_path(@event)
    else
      render 'events/show', status: :unprocessable_entity
    end
  end

  private

  def participant_params
    params.require(:participant).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/events/assigning.html.erb
<p>If the group admin should not see the pairings:</p>

<h1>The mails with the pairs have been sent!</h1>
<h1>Thank you for playing.</h1>

<p>If the group admin can see who has who:</p>

<% @participants.each do |participant| %>
<h1> <%=participant.name%> has to give a gift to <%=participant.target%> .</h1>
<% end %>


<%= link_to "Back to list", events_path, class: "btn btn-primary" %>

app/views/events/index.html.erb
<h1>All Games</h1>
<p>Add as many games as you want (friends, office, sports club):</p>
<hr>

<div class="flex-index">
  <%= link_to "+ Add a new game", new_event_path, class: "btn btn-primary"%>
</div>

<div class="flex-index">
  <div class="card-event">
    <ul class="list-index">
      <% @events.each do |event| %>
        <li><%=link_to event.title, event_path(event), class: "li-index" %></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/events/new.html.erb
<%= simple_form_for(@event) do |f| %>
  <%= f.input :title %>
  <%= f.input :maximum_amount %>
  <%= f.submit %>
<% end %>

<hr>

<%= link_to "Back to list", events_path %>

app/views/events/show.html.erb
<h1>Event:</h1>
<hr>
<h4>Title -> <%= @event.title %></h4>
<h4>Maximum Amount -> <%= @event.maximum_amount %> €</h4>

<p>Participants:</p>
<ul>
  <% @event.participants.each do |participant| %>
    <li><%=participant.name%> - <%=participant.email%></li>
  <% end %>
</ul>

<%= link_to "Assign Buddies", event_pairs_path(@event), class: "btn btn-primary"%>

<hr>

<h3>Add a new participant:</h3>

<%= simple_form_for [@event, @participant] do |f| %>
  <%= f.input :name %>
  <%= f.input :email %>
  <%= f.submit %>
<% end %>

<hr>

<%= link_to "Delete", event_path(@event), class: "btn btn-primary", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>

<%= link_to "Back to Events", events_path(@event), class: "btn btn-primary"%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SecretSanta</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body><%= render "shared/navbar" %>
<%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse4.mm.bing.net%2Fth%3Fid%3DOIP.Ir5jGkxaYAyG7W9NFkqWlAHaEc%26pid%3DApi&f=1&ipt=5ed53eb6f3fe97b5eb20f3d578845618f71ac564247982e182e1243cb11f41d8&ipo=images);">
  <div class="container">
    <h1>Welcome to <strong>Secret Santa</strong>!</h1>
    <p>Set up a game, add your friends and enjoy the christmas time.</p>
    <%= link_to "Create a game", events_path(@event), class: "btn btn-primary"%>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fimg.rawpixel.com%2Fs3fs-private%2Frawpixel_images%2Fwebsite_content%2Fv767-wan-57_1.png%3Fauto%3D%26bg%3Dtransparent%26con%3D3%26cs%3Dsrgb%26dpr%3D1%26fm%3Dpng%26ixlib%3Dphp-3.1.0%26mark%3Drawpixel-watermark.png%26markalpha%3D90%26markpad%3D13%26markscale%3D10%26markx%3D25%26q%3D75%26usm%3D15%26vib%3D3%26w%3D1400%26s%3D7c579e9d7fc1b37e9b65b0a45729d49b&f=1&nofb=1&ipt=bdf62de0c88f6818b9e9d490b16f670a7cae0308975d2edbfcf80fa0e6ecf7d9&ipo=images" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/gideonmaydell", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Back to homepage", root_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>